---
title: "night of"
author: "Keith"
date: "5/27/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("helper_functions.R")
source("constants.R")
googlesheets4::gs4_auth(email = "keith.gordon.williams@gmail.com", use_oob = TRUE)
```

# Pre-game

```{r}
# read in ledger
starting_ledger <- googlesheets4::read_sheet(sheet_path, sheet = "ledger")
```

```{r}
player_balance(starting_ledger) %>% knitr::kable()
```

# During Game

## Ledger

```{r}
# nightly ledger
tonight_date <- "2020-05-27"
tonight <- empty_ledger
```

## Chip Values

```{r}
chips <- tribble(
    ~player,  ~chips,
    "keith",  0,
    "dustin", 0,
    "devon",  0,
    "hanson", 0
)

(total_chips <- sum(chips$chips))
(pot <- get_money_on_table(tonight))
big_blind <- 100

# calculate a $40 buyin in chips
calculate_buyin(total_chips, pot, 40)

# calculate minimum buyin value
value_chips(total_chips, pot, chips = 4000)

# calculate big blind value
value_chips(total_chips, pot, chips = big_blind)

# table balance
chips_to_dollars(chips, pot) %>% 
    knitr::kable()
```

# Post-Game

```{r}
# confirm transactions look right
knitr::kable(tonight)

# new balance
balance <- bind_rows(starting_ledger, tonight) %>%
    player_balance()

knitr::kable(balance)
```

```{r}
# Write tonight's transactions to the ledger
googlesheets4::sheet_append(sheet_path, tonight, sheet = "ledger")

# Write the player aggregated balance to the ledger
googlesheets4::write_sheet(balance, sheet_path, sheet = "balance")
```

